import { App } from 'vue'
import {
    // NA,
    // NAffix,
    // NAlert,
    // NAnchor,
    // NAnchorLink,
    // NAutoComplete,
    // NAvatar,
    // NBackTop,
    // NBadge,
    // NBlockquote,
    // NBreadcrumb,
    // NBreadcrumbItem,
    NButton,
    // NButtonGroup,
    // NCalendar,
    NCard,
    // NCarousel,
    // NCascader,
    // NCheckbox,
    // NCheckboxGroup,
    // NCode,
    NCol,
    // NCollapse,
    // NCollapseItem,
    // NColorPicker,
    // NConfigProvider,
    // NDataTable,
    // NDatePicker,
    // NDescriptions,
    // NDescriptionsItem,
    // NDialog,
    // NDialogProvider,
    // NDivider,
    // NDrawer,
    // NDrawerContent,
    // NDropdown,
    // NDynamicInput,
    // NDynamicTags,
    // NElement,
    // NEllipsis,
    // NEmpty,
    // NForm,
    // NFormItem,
    // NFormItemCol,
    // NFormItemGi,
    // NFormItemGridItem,
    // NFormItemRow,
    // NGi,
    // NGlobalStyle,
    NGradientText,
    // NGrid,
    // NGridItem,
    // NH1,
    // NH2,
    // NH3,
    // NH4,
    // NH5,
    // NH6,
    // NHr,
    NIcon,
    // NImage,
    // NImageGroup,
    // NInput,
    // NInputGroup,
    // NInputGroupLabel,
    // NInputNumber,
    // NLayout,
    // NLayoutContent,
    // NLayoutFooter,
    // NLayoutHeader,
    // NLayoutSider,
    // NLi,
    // NList,
    // NListItem,
    // NLoadingBarProvider,
    // NLog,
    // NMention,
    // NMenu,
    NMessageProvider,
    // NModal,
    // NNotificationProvider,
    // NOl,
    // NP,
    // NPageHeader,
    // NPagination,
    // NPopconfirm,
    // NPopover,
    // NPopselect,
    NProgress,
    // NRadio,
    // NRadioButton,
    // NRadioGroup,
    // NRate,
    // NResult,
    NRow,
    // NScrollbar,
    // NSelect,
    NSkeleton,
    // NSlider,
    NSpace,
    // NSpin,
    NStatistic,
    // NStep,
    // NSteps,
    NSwitch,
    // NTabPane,
    // NTable,
    // NTabs,
    // NTag,
    // NTbody,
    // NTd,
    // NText,
    // NTh,
    // NThead,
    // NThemeEditor,
    // NThing,
    // NTime,
    // NTimePicker,
    // NTimeline,
    // NTimelineItem,
    // NTooltip,
    // NTr,
    // NTransfer,
    // NTree,
    // NTreeSelect,
    // NUl,
    // NUpload,
    // NUploadDragger,
    // NxButton,
    // NxScrollbar,
    useNotification,
    useMessage
} from 'naive-ui'

const components = [
    // NA,
    // NAffix,
    // NAlert,
    // NAnchor,
    // NAnchorLink,
    // NAutoComplete,
    // NAvatar,
    // NBackTop,
    // NBadge,
    // NBlockquote,
    // NBreadcrumb,
    // NBreadcrumbItem,
    NButton,
    // NButtonGroup,
    // NCalendar,
    NCard,
    // NCarousel,
    // NCascader,
    // NCheckbox,
    // NCheckboxGroup,
    // NCode,
    NCol,
    // NCollapse,
    // NCollapseItem,
    // NColorPicker,
    // NConfigProvider,
    // NDataTable,
    // NDatePicker,
    // NDescriptions,
    // NDescriptionsItem,
    // NDialog,
    // NDialogProvider,
    // NDivider,
    // NDrawer,
    // NDrawerContent,
    // NDropdown,
    // NDynamicInput,
    // NDynamicTags,
    // NElement,
    // NEllipsis,
    // NEmpty,
    // NForm,
    // NFormItem,
    // NFormItemCol,
    // NFormItemGi,
    // NFormItemGridItem,
    // NFormItemRow,
    // NGi,
    // NGlobalStyle,
    NGradientText,
    // NGrid,
    // NGridItem,
    // NH1,
    // NH2,
    // NH3,
    // NH4,
    // NH5,
    // NH6,
    // NHr,
    NIcon,
    // NImage,
    // NImageGroup,
    // NInput,
    // NInputGroup,
    // NInputGroupLabel,
    // NInputNumber,
    // NLayout,
    // NLayoutContent,
    // NLayoutFooter,
    // NLayoutHeader,
    // NLayoutSider,
    // NLi,
    // NList,
    // NListItem,
    // NLoadingBarProvider,
    // NLog,
    // NMention,
    // NMenu,
    NMessageProvider,
    // NModal,
    // NNotificationProvider,
    // NOl,
    // NP,
    // NPageHeader,
    // NPagination,
    // NPopconfirm,
    // NPopover,
    // NPopselect,
    NProgress,
    // NRadio,
    // NRadioButton,
    // NRadioGroup,
    // NRate,
    // NResult,
    NRow,
    // NScrollbar,
    // NSelect,
    NSkeleton,
    // NSlider,
    NSpace,
    // NSpin,
    NStatistic,
    // NStep,
    // NSteps,
    NSwitch,
    // NTabPane,
    // NTable,
    // NTabs,
    // NTag,
    // NTbody,
    // NTd,
    // NText,
    // NTh,
    // NThead,
    // NThemeEditor,
    // NThing,
    // NTime,
    // NTimePicker,
    // NTimeline,
    // NTimelineItem,
    // NTooltip,
    // NTr,
    // NTransfer,
    // NTree,
    // NTreeSelect,
    // NUl,
    // NUpload,
    // NUploadDragger,
    // NxButton,
    // NxScrollbar,
    useNotification,
    useMessage
]

const plugins = [useNotification, useMessage]

// window.message = useMessage()

export default {
    install: (app: App) => {
        components.forEach((component) => app.component('N' + component.name, component))
        plugins.forEach((plugin) => app.use(plugin))
    }
}
